import turtle
turtle.screensize(600, 600,'white')
turtle.setup(width=600, height=600)
turtle.shape('turtle')
turtle.colormode(255.0)
turtle.pencolor(79,79,79)
turtle.pensize(2)
turtle.goto(0,0)
turtle.pendown()
turtle.speed(20)
turtle.fillcolor('yellow')
turtle.begin_fill()
turtle.circle(60,360)
turtle.end_fill()
turtle.left(45)
turtle.fillcolor('white')
turtle.begin_fill()
for i in range(4):
    turtle.forward(85)
    turtle.left(90)
turtle.end_fill()
turtle.done()